const quizData=[
{"block":1,"title":"Legislación y Servicios Sociales","icon":"⚖️","range":"1-60","questions":[
{id:1,q:"El órgano que ostenta la máxima representación del Ayuntamiento es:",o:[{l:"A",t:"El Pleno"},{l:"B",t:"La Junta de Gobierno"},{l:"C",t:"El Alvarado"},{l:"D",t:"El Secretario"}],c:"C"},
{id:2,q:"El órgano colegiado de control político es:",o:[{l:"A",t:"Alcaldía"},{l:"B",t:"Pleno"},{l:"C",t:"Teniente de Alvarado"},{l:"D",t:"Intervención"}],c:"B"},
{id:3,q:"¿Quién sustituye al Alvarado?",o:[{l:"A",t:"Secretario"},{l:"B",t:"Concejal delegado"},{l:"C",t:"Teniente de Alvarado"},{l:"D",t:"Interventor"}],c:"C"},
{id:4,q:"La Junta de Gobierno Local tiene funciones:",o:[{l:"A",t:"Legislativas"},{l:"B",t:"Judiciales"},{l:"C",t:"Ejecutivas"},{l:"D",t:"Electorales"}],c:"C"},
{id:5,q:"La Ley que regula las bases del régimen local es:",o:[{l:"A",t:"Ley 39/2015"},{l:"B",t:"Ley 7/1985"},{l:"C",t:"Ley 40/2015"},{l:"D",t:"Ley 16/2019"}],c:"B"},
{id:6,q:"El Estatuto Básico del Empleado Público regula:",o:[{l:"A",t:"Urbanismo"},{l:"B",t:"Funcionarios y personal público"},{l:"C",t:"Sanidad"},{l:"D",t:"Educación"}],c:"B"},
{id:7,q:"Un principio del empleado público es:",o:[{l:"A",t:"Parcialidad"},{l:"B",t:"Subjetividad"},{l:"C",t:"Imparcialidad"},{l:"D",t:"Arbitrio"}],c:"C"},
{id:8,q:"La confidencialidad implica:",o:[{l:"A",t:"Compartir información"},{l:"B",t:"Guardar secreto profesional"},{l:"C",t:"Publicar datos"},{l:"D",t:"Delegar funciones"}],c:"B"},
{id:9,q:"La discriminación indirecta es:",o:[{l:"A",t:"Directa y evidente"},{l:"B",t:"Oculta en normas aparentemente neutras"},{l:"C",t:"Legal"},{l:"D",t:"Obligatoria"}],c:"B"},
{id:10,q:"La Ley 3/2007 trata sobre:",o:[{l:"A",t:"Dependencia"},{l:"B",t:"Igualdad"},{l:"C",t:"Sanidad"},{l:"D",t:"Educación"}],c:"B"},
{id:11,q:"La Ley 4/2023 regula:",o:[{l:"A",t:"Urbanismo"},{l:"B",t:"Derechos LGTBI"},{l:"C",t:"Hacienda"},{l:"D",t:"Seguridad"}],c:"B"},
{id:12,q:"La identidad de género es:",o:[{l:"A",t:"Sexo biológico"},{l:"B",t:"Percepción personal"},{l:"C",t:"Nacionalidad"},{l:"D",t:"Edad"}],c:"B"},
{id:13,q:"La Ley de Servicios Sociales de Canarias es:",o:[{l:"A",t:"7/1985"},{l:"B",t:"16/2019"},{l:"C",t:"39/2015"},{l:"D",t:"14/1986"}],c:"B"},
{id:14,q:"El sistema de servicios sociales garantiza:",o:[{l:"A",t:"Beneficio económico"},{l:"B",t:"Bienestar social"},{l:"C",t:"Exclusión"},{l:"D",t:"Competencia"}],c:"B"},
{id:15,q:"Un derecho del usuario es:",o:[{l:"A",t:"Desobedecer normas"},{l:"B",t:"Atención digna"},{l:"C",t:"Negligencia"},{l:"D",t:"Abandono"}],c:"B"},
{id:16,q:"Un deber del usuario es:",o:[{l:"A",t:"Uso adecuado del servicio"},{l:"B",t:"Ignorar normas"},{l:"C",t:"No colaborar"},{l:"D",t:"Ocultar datos"}],c:"A"},
{id:17,q:"La teleasistencia es:",o:[{l:"A",t:"Atención hospitalaria"},{l:"B",t:"Atención a distancia"},{l:"C",t:"Servicio judicial"},{l:"D",t:"Servicio educativo"}],c:"B"},
{id:18,q:"Los centros de día pertenecen a:",o:[{l:"A",t:"Educación"},{l:"B",t:"Servicios sociales"},{l:"C",t:"Justicia"},{l:"D",t:"Transporte"}],c:"B"},
{id:19,q:"La inspección de servicios sociales garantiza:",o:[{l:"A",t:"Publicidad"},{l:"B",t:"Calidad"},{l:"C",t:"Negligencia"},{l:"D",t:"Privacidad"}],c:"B"},
{id:20,q:"Un CED es:",o:[{l:"A",t:"Centro hospitalario"},{l:"B",t:"Servicio diurno"},{l:"C",t:"Centro educativo"},{l:"D",t:"Centro penitenciario"}],c:"B"},
{id:21,q:"Objetivo del CED:",o:[{l:"A",t:"Aislar"},{l:"B",t:"Fomentar autonomía"},{l:"C",t:"Hospitalizar"},{l:"D",t:"Judicializar"}],c:"B"},
{id:22,q:"El usuario típico es:",o:[{l:"A",t:"Niño"},{l:"B",t:"Adulto sano"},{l:"C",t:"Persona dependiente"},{l:"D",t:"Deportista"}],c:"C"},
{id:23,q:"Un servicio del CED:",o:[{l:"A",t:"Cirugía"},{l:"B",t:"Terapia ocupacional"},{l:"C",t:"Juicio"},{l:"D",t:"Educación primaria"}],c:"B"},
{id:24,q:"El auxiliar realiza:",o:[{l:"A",t:"Diagnóstico médico"},{l:"B",t:"Higiene"},{l:"C",t:"Prescripción"},{l:"D",t:"Cirugía"}],c:"B"},
{id:25,q:"El envejecimiento es:",o:[{l:"A",t:"Reversible"},{l:"B",t:"Irreversible"},{l:"C",t:"Opcional"},{l:"D",t:"Artificial"}],c:"B"},
{id:26,q:"Un cambio físico:",o:[{l:"A",t:"Aumento de fuerza"},{l:"B",t:"Pérdida de movilidad"},{l:"C",t:"Crecimiento"},{l:"D",t:"Regeneración"}],c:"B"},
{id:27,q:"Una necesidad biológica:",o:[{l:"A",t:"Afecto"},{l:"B",t:"Alimentación"},{l:"C",t:"Participación"},{l:"D",t:"Comunicación"}],c:"B"},
{id:28,q:"Necesidad social:",o:[{l:"A",t:"Dormir"},{l:"B",t:"Comer"},{l:"C",t:"Relacionarse"},{l:"D",t:"Respirar"}],c:"C"},
{id:29,q:"Necesidad psicológica:",o:[{l:"A",t:"Comer"},{l:"B",t:"Seguridad"},{l:"C",t:"Dormir"},{l:"D",t:"Beber"}],c:"B"},
{id:30,q:"La demencia es:",o:[{l:"A",t:"Aguda"},{l:"B",t:"Crónica"},{l:"C",t:"Reversible"},{l:"D",t:"Temporal"}],c:"B"},
{id:31,q:"El delirium es:",o:[{l:"A",t:"Crónico"},{l:"B",t:"Agudo"},{l:"C",t:"Permanente"},{l:"D",t:"Genético"}],c:"B"},
{id:32,q:"Ejemplo de demencia:",o:[{l:"A",t:"Gripe"},{l:"B",t:"Enfermedad de Alzheimer"},{l:"C",t:"Fractura"},{l:"D",t:"Asma"}],c:"B"},
{id:33,q:"La depresión en ancianos es:",o:[{l:"A",t:"Rara"},{l:"B",t:"Frecuente"},{l:"C",t:"Inexistente"},{l:"D",t:"Obligatoria"}],c:"B"},
{id:34,q:"Tipo de maltrato:",o:[{l:"A",t:"Educativo"},{l:"B",t:"Físico"},{l:"C",t:"Deportivo"},{l:"D",t:"Cultural"}],c:"B"},
{id:35,q:"La negligencia es:",o:[{l:"A",t:"Cuidado adecuado"},{l:"B",t:"Falta de atención"},{l:"C",t:"Protección"},{l:"D",t:"Respeto"}],c:"B"},
{id:36,q:"Factor de riesgo:",o:[{l:"A",t:"Independencia"},{l:"B",t:"Aislamiento"},{l:"C",t:"Salud"},{l:"D",t:"Autonomía"}],c:"B"},
{id:37,q:"Paciente crónico:",o:[{l:"A",t:"Enfermedad corta"},{l:"B",t:"Enfermedad prolongada"},{l:"C",t:"Enfermedad leve"},{l:"D",t:"Enfermedad puntual"}],c:"B"},
{id:38,q:"Cuidados paliativos buscan:",o:[{l:"A",t:"Curar"},{l:"B",t:"Calidad de vida"},{l:"C",t:"Operar"},{l:"D",t:"Investigar"}],c:"B"},
{id:39,q:"Función del auxiliar:",o:[{l:"A",t:"Operar"},{l:"B",t:"Confort"},{l:"C",t:"Diagnosticar"},{l:"D",t:"Prescribir"}],c:"B"},
{id:40,q:"El Pleno aprueba:",o:[{l:"A",t:"Diagnósticos"},{l:"B",t:"Presupuestos"},{l:"C",t:"Tratamientos"},{l:"D",t:"Recetas"}],c:"B"},
{id:41,q:"La igualdad implica:",o:[{l:"A",t:"Discriminación"},{l:"B",t:"Trato equitativo"},{l:"C",t:"Exclusión"},{l:"D",t:"Jerarquía"}],c:"B"},
{id:42,q:"La participación del mayor pertenece a:",o:[{l:"A",t:"ONU"},{l:"B",t:"Policía"},{l:"C",t:"Tráfico"},{l:"D",t:"Educación"}],c:"A"},
{id:43,q:"El aislamiento aumenta:",o:[{l:"A",t:"Bienestar"},{l:"B",t:"Riesgo"},{l:"C",t:"Salud"},{l:"D",t:"Autonomía"}],c:"B"},
{id:44,q:"El envejecimiento social incluye:",o:[{l:"A",t:"Músculos"},{l:"B",t:"Relaciones"},{l:"C",t:"Órganos"},{l:"D",t:"Genes"}],c:"B"},
{id:45,q:"El auxiliar debe:",o:[{l:"A",t:"Ignorar"},{l:"B",t:"Observar"},{l:"C",t:"Diagnosticar"},{l:"D",t:"Recetar"}],c:"B"},
{id:46,q:"El delirium es:",o:[{l:"A",t:"Progresivo"},{l:"B",t:"Brusco"},{l:"C",t:"Lento"},{l:"D",t:"Crónico"}],c:"B"},
{id:47,q:"El maltrato psicológico incluye:",o:[{l:"A",t:"Golpes"},{l:"B",t:"Insultos"},{l:"C",t:"Medicación"},{l:"D",t:"Dieta"}],c:"B"},
{id:48,q:"La autonomía es:",o:[{l:"A",t:"Dependencia"},{l:"B",t:"Capacidad funcional"},{l:"C",t:"Enfermedad"},{l:"D",t:"Dolor"}],c:"B"},
{id:49,q:"La atención centrada en la persona implica:",o:[{l:"A",t:"Rutina rígida"},{l:"B",t:"Individualización"},{l:"C",t:"Abandono"},{l:"D",t:"Masificación"}],c:"B"},
{id:50,q:"El sistema social busca:",o:[{l:"A",t:"Exclusión"},{l:"B",t:"Inclusión"},{l:"C",t:"Aislamiento"},{l:"D",t:"Competencia"}],c:"B"},
{id:51,q:"La dignidad implica:",o:[{l:"A",t:"Desprecio"},{l:"B",t:"Respeto"},{l:"C",t:"Castigo"},{l:"D",t:"Abandono"}],c:"B"},
{id:52,q:"Un centro de día evita:",o:[{l:"A",t:"Atención"},{l:"B",t:"Institucionalización"},{l:"C",t:"Cuidados"},{l:"D",t:"Relación"}],c:"B"},
{id:53,q:"El auxiliar no debe:",o:[{l:"A",t:"Observar"},{l:"B",t:"Cuidar"},{l:"C",t:"Diagnosticar"},{l:"D",t:"Ayudar"}],c:"C"},
{id:54,q:"El apoyo emocional es:",o:[{l:"A",t:"Secundario"},{l:"B",t:"Fundamental"},{l:"C",t:"Innecesario"},{l:"D",t:"Opcional"}],c:"B"},
{id:55,q:"El deterioro cognitivo afecta:",o:[{l:"A",t:"Músculos"},{l:"B",t:"Memoria"},{l:"C",t:"Huesos"},{l:"D",t:"Piel"}],c:"B"},
{id:56,q:"La prevención del maltrato incluye:",o:[{l:"A",t:"Ignorar"},{l:"B",t:"Detectar"},{l:"C",t:"Ocultar"},{l:"D",t:"Evitar intervención"}],c:"B"},
{id:57,q:"El trabajo en equipo es:",o:[{l:"A",t:"Individual"},{l:"B",t:"Interdisciplinar"},{l:"C",t:"Aislado"},{l:"D",t:"Autónomo"}],c:"B"},
{id:58,q:"La calidad del servicio implica:",o:[{l:"A",t:"Error"},{l:"B",t:"Mejora continua"},{l:"C",t:"Abandono"},{l:"D",t:"Improvisación"}],c:"B"},
{id:59,q:"La dependencia implica:",o:[{l:"A",t:"Autonomía"},{l:"B",t:"Necesidad de ayuda"},{l:"C",t:"Independencia"},{l:"D",t:"Salud"}],c:"B"},
{id:60,q:"El objetivo final es:",o:[{l:"A",t:"Curar siempre"},{l:"B",t:"Bienestar"},{l:"C",t:"Aislar"},{l:"D",t:"Controlar"}],c:"B"}
]},
{"block":2,"title":"Legislación Avanzada","icon":"📋","range":"61-120","questions":[
{id:61,q:"Según la Ley 7/1985, el municipio es:",o:[{l:"A",t:"Entidad privada"},{l:"B",t:"Entidad básica de organización territorial del Estado"},{l:"C",t:"Órgano autonómico"},{l:"D",t:"Administración sanitaria"}],c:"B"},
{id:62,q:"El Alvarado es elegido por:",o:[{l:"A",t:"Ciudadanos directamente siempre"},{l:"B",t:"El Pleno entre sus miembros"},{l:"C",t:"El Gobierno"},{l:"D",t:"El Cabildo"}],c:"B"},
{id:63,q:"El control y fiscalización corresponde a:",o:[{l:"A",t:"Alcalde"},{l:"B",t:"Junta de Gobierno"},{l:"C",t:"Pleno"},{l:"D",t:"Secretario"}],c:"C"},
{id:64,q:"El personal laboral se rige por:",o:[{l:"A",t:"Derecho administrativo"},{l:"B",t:"Derecho laboral"},{l:"C",t:"Derecho penal"},{l:"D",t:"Derecho civil"}],c:"B"},
{id:65,q:"El principio de integridad implica:",o:[{l:"A",t:"Actuar con parcialidad"},{l:"B",t:"Actuar con honradez"},{l:"C",t:"Delegar funciones"},{l:"D",t:"Omitir información"}],c:"B"},
{id:66,q:"El incumplimiento del código puede dar lugar a:",o:[{l:"A",t:"Premio"},{l:"B",t:"Sanción disciplinaria"},{l:"C",t:"Ascenso"},{l:"D",t:"Incentivo"}],c:"B"},
{id:67,q:"La discriminación indirecta se produce cuando:",o:[{l:"A",t:"Se discrimina abiertamente"},{l:"B",t:"Una norma perjudica sin intención"},{l:"C",t:"Se protege a un grupo"},{l:"D",t:"Se favorece igualdad"}],c:"B"},
{id:68,q:"Las acciones positivas son:",o:[{l:"A",t:"Discriminatorias ilegales"},{l:"B",t:"Medidas para corregir desigualdades"},{l:"C",t:"Sanciones"},{l:"D",t:"Obligaciones penales"}],c:"B"},
{id:69,q:"El acoso por razón de sexo es:",o:[{l:"A",t:"Delito siempre"},{l:"B",t:"Conducta que atenta contra la dignidad"},{l:"C",t:"Derecho laboral"},{l:"D",t:"Acto administrativo"}],c:"B"},
{id:70,q:"La orientación sexual se refiere a:",o:[{l:"A",t:"Identidad"},{l:"B",t:"Atracción afectiva"},{l:"C",t:"Sexo biológico"},{l:"D",t:"Nacionalidad"}],c:"B"},
{id:71,q:"La Ley 16/2019 define el sistema como:",o:[{l:"A",t:"Cerrado"},{l:"B",t:"Universal"},{l:"C",t:"Privado"},{l:"D",t:"Limitado"}],c:"B"},
{id:72,q:"La intervención social debe ser:",o:[{l:"A",t:"Individual"},{l:"B",t:"Interdisciplinar"},{l:"C",t:"Aislada"},{l:"D",t:"Judicial"}],c:"B"},
{id:73,q:"El catálogo de servicios es:",o:[{l:"A",t:"Opcional"},{l:"B",t:"Vinculante"},{l:"C",t:"Privado"},{l:"D",t:"Limitado"}],c:"B"},
{id:74,q:"La planificación del sistema busca:",o:[{l:"A",t:"Improvisación"},{l:"B",t:"Organización eficiente"},{l:"C",t:"Reducción de servicios"},{l:"D",t:"Privatización"}],c:"B"},
{id:75,q:"La inspección tiene carácter:",o:[{l:"A",t:"Voluntario"},{l:"B",t:"Obligatorio"},{l:"C",t:"Opcional"},{l:"D",t:"Privado"}],c:"B"},
{id:76,q:"La calidad en servicios sociales implica:",o:[{l:"A",t:"Estabilidad"},{l:"B",t:"Mejora continua"},{l:"C",t:"Reducción de costes"},{l:"D",t:"Control policial"}],c:"B"},
{id:77,q:"El objetivo principal del CED es:",o:[{l:"A",t:"Curar enfermedades"},{l:"B",t:"Mantener autonomía"},{l:"C",t:"Hospitalizar"},{l:"D",t:"Diagnosticar"}],c:"B"},
{id:78,q:"El CED actúa principalmente en:",o:[{l:"A",t:"Atención primaria sanitaria"},{l:"B",t:"Atención social"},{l:"C",t:"Atención judicial"},{l:"D",t:"Educación"}],c:"B"},
{id:79,q:"El acceso al CED se basa en:",o:[{l:"A",t:"Edad únicamente"},{l:"B",t:"Situación de dependencia"},{l:"C",t:"Nivel económico"},{l:"D",t:"Nacionalidad"}],c:"B"},
{id:80,q:"El apoyo a la familia es:",o:[{l:"A",t:"Secundario"},{l:"B",t:"Objetivo del servicio"},{l:"C",t:"Opcional"},{l:"D",t:"Innecesario"}],c:"B"},
{id:81,q:"El envejecimiento activo implica:",o:[{l:"A",t:"Inactividad"},{l:"B",t:"Participación"},{l:"C",t:"Dependencia"},{l:"D",t:"Aislamiento"}],c:"B"},
{id:82,q:"La fragilidad se relaciona con:",o:[{l:"A",t:"Fuerza elevada"},{l:"B",t:"Vulnerabilidad"},{l:"C",t:"Independencia"},{l:"D",t:"Juventud"}],c:"B"},
{id:83,q:"El envejecimiento psicológico afecta a:",o:[{l:"A",t:"Órganos"},{l:"B",t:"Conducta y emociones"},{l:"C",t:"Huesos"},{l:"D",t:"Piel"}],c:"B"},
{id:84,q:"La jubilación influye en:",o:[{l:"A",t:"Biología"},{l:"B",t:"Área social"},{l:"C",t:"Genética"},{l:"D",t:"Fisiología"}],c:"B"},
{id:85,q:"La necesidad de afecto es:",o:[{l:"A",t:"Biológica"},{l:"B",t:"Psicológica"},{l:"C",t:"Social"},{l:"D",t:"Física"}],c:"B"},
{id:86,q:"La necesidad de higiene es:",o:[{l:"A",t:"Psicológica"},{l:"B",t:"Social"},{l:"C",t:"Biológica"},{l:"D",t:"Cultural"}],c:"C"},
{id:87,q:"La falta de relaciones provoca:",o:[{l:"A",t:"Mejora"},{l:"B",t:"Aislamiento"},{l:"C",t:"Autonomía"},{l:"D",t:"Independencia"}],c:"B"},
{id:88,q:"El delirium se caracteriza por:",o:[{l:"A",t:"Inicio lento"},{l:"B",t:"Inicio brusco"},{l:"C",t:"Curso estable"},{l:"D",t:"Irreversibilidad"}],c:"B"},
{id:89,q:"La demencia afecta principalmente a:",o:[{l:"A",t:"Sistema digestivo"},{l:"B",t:"Funciones cognitivas"},{l:"C",t:"Sistema muscular"},{l:"D",t:"Piel"}],c:"B"},
{id:90,q:"La reversibilidad es propia de:",o:[{l:"A",t:"Demencia"},{l:"B",t:"Delirium"},{l:"C",t:"Alzheimer"},{l:"D",t:"Parkinson"}],c:"B"},
{id:91,q:"La desorientación es típica de:",o:[{l:"A",t:"Bienestar"},{l:"B",t:"Trastornos cognitivos"},{l:"C",t:"Salud"},{l:"D",t:"Nutrición"}],c:"B"},
{id:92,q:"El maltrato económico consiste en:",o:[{l:"A",t:"Golpear"},{l:"B",t:"Uso indebido de dinero"},{l:"C",t:"Insultar"},{l:"D",t:"Ignorar"}],c:"B"},
{id:93,q:"El aislamiento favorece:",o:[{l:"A",t:"Protección"},{l:"B",t:"Maltrato"},{l:"C",t:"Autonomía"},{l:"D",t:"Salud"}],c:"B"},
{id:94,q:"La detección precoz corresponde a:",o:[{l:"A",t:"Policía"},{l:"B",t:"Profesionales"},{l:"C",t:"Jueces"},{l:"D",t:"Familia solo"}],c:"B"},
{id:95,q:"El objetivo de cuidados paliativos es:",o:[{l:"A",t:"Curación"},{l:"B",t:"Confort"},{l:"C",t:"Cirugía"},{l:"D",t:"Diagnóstico"}],c:"B"},
{id:96,q:"El dolor en paciente terminal debe:",o:[{l:"A",t:"Ignorarse"},{l:"B",t:"Controlarse"},{l:"C",t:"Evitarse"},{l:"D",t:"Posponerse"}],c:"B"},
{id:97,q:"El apoyo familiar es:",o:[{l:"A",t:"Opcional"},{l:"B",t:"Fundamental"},{l:"C",t:"Secundario"},{l:"D",t:"Irrelevante"}],c:"B"},
{id:98,q:"El trabajo interdisciplinar implica:",o:[{l:"A",t:"Individual"},{l:"B",t:"Equipo"},{l:"C",t:"Aislado"},{l:"D",t:"Autónomo"}],c:"B"},
{id:99,q:"La autonomía significa:",o:[{l:"A",t:"Dependencia"},{l:"B",t:"Capacidad de decisión"},{l:"C",t:"Enfermedad"},{l:"D",t:"Dolor"}],c:"B"},
{id:100,q:"El respeto a la dignidad implica:",o:[{l:"A",t:"Ignorar"},{l:"B",t:"Valorar a la persona"},{l:"C",t:"Controlar"},{l:"D",t:"Aislar"}],c:"B"},
{id:101,q:"El auxiliar forma parte de:",o:[{l:"A",t:"Equipo judicial"},{l:"B",t:"Equipo asistencial"},{l:"C",t:"Equipo político"},{l:"D",t:"Equipo económico"}],c:"B"},
{id:102,q:"La calidad asistencial busca:",o:[{l:"A",t:"Reducción"},{l:"B",t:"Mejora"},{l:"C",t:"Eliminación"},{l:"D",t:"Privatización"}],c:"B"},
{id:103,q:"La dependencia se valora según:",o:[{l:"A",t:"Edad"},{l:"B",t:"Necesidad de ayuda"},{l:"C",t:"Sexo"},{l:"D",t:"Cultura"}],c:"B"},
{id:104,q:"El deterioro funcional afecta a:",o:[{l:"A",t:"Autonomía"},{l:"B",t:"Genética"},{l:"C",t:"Cultura"},{l:"D",t:"Economía"}],c:"A"},
{id:105,q:"La atención centrada en la persona implica:",o:[{l:"A",t:"Estandarizar"},{l:"B",t:"Individualizar"},{l:"C",t:"Generalizar"},{l:"D",t:"Automatizar"}],c:"B"},
{id:106,q:"El bienestar incluye:",o:[{l:"A",t:"Solo físico"},{l:"B",t:"Integral"},{l:"C",t:"Parcial"},{l:"D",t:"Económico"}],c:"B"},
{id:107,q:"La participación social evita:",o:[{l:"A",t:"Salud"},{l:"B",t:"Aislamiento"},{l:"C",t:"Autonomía"},{l:"D",t:"Relación"}],c:"B"},
{id:108,q:"El envejecimiento activo promueve:",o:[{l:"A",t:"Dependencia"},{l:"B",t:"Actividad"},{l:"C",t:"Aislamiento"},{l:"D",t:"Enfermedad"}],c:"B"},
{id:109,q:"El auxiliar debe observar:",o:[{l:"A",t:"Solo síntomas"},{l:"B",t:"Cambios globales"},{l:"C",t:"Solo conducta"},{l:"D",t:"Solo físico"}],c:"B"},
{id:110,q:"La intervención social busca:",o:[{l:"A",t:"Exclusión"},{l:"B",t:"Inclusión"},{l:"C",t:"Separación"},{l:"D",t:"Control"}],c:"B"},
{id:111,q:"La comunicación con el anciano debe ser:",o:[{l:"A",t:"Rápida"},{l:"B",t:"Clara"},{l:"C",t:"Técnica"},{l:"D",t:"Compleja"}],c:"B"},
{id:112,q:"El apoyo emocional mejora:",o:[{l:"A",t:"Aislamiento"},{l:"B",t:"Bienestar"},{l:"C",t:"Enfermedad"},{l:"D",t:"Dependencia"}],c:"B"},
{id:113,q:"La fragilidad aumenta:",o:[{l:"A",t:"Resistencia"},{l:"B",t:"Riesgo"},{l:"C",t:"Fuerza"},{l:"D",t:"Autonomía"}],c:"B"},
{id:114,q:"La ética profesional implica:",o:[{l:"A",t:"Interés propio"},{l:"B",t:"Responsabilidad"},{l:"C",t:"Beneficio económico"},{l:"D",t:"Autoridad"}],c:"B"},
{id:115,q:"El respeto a la intimidad implica:",o:[{l:"A",t:"Exposición"},{l:"B",t:"Privacidad"},{l:"C",t:"Publicidad"},{l:"D",t:"Difusión"}],c:"B"},
{id:116,q:"La intervención precoz evita:",o:[{l:"A",t:"Mejora"},{l:"B",t:"Deterioro"},{l:"C",t:"Autonomía"},{l:"D",t:"Salud"}],c:"B"},
{id:117,q:"El auxiliar debe fomentar:",o:[{l:"A",t:"Dependencia"},{l:"B",t:"Autonomía"},{l:"C",t:"Aislamiento"},{l:"D",t:"Pasividad"}],c:"B"},
{id:118,q:"El entorno influye en:",o:[{l:"A",t:"Salud"},{l:"B",t:"Bienestar"},{l:"C",t:"Ambos"},{l:"D",t:"Ninguno"}],c:"C"},
{id:119,q:"La calidad de vida incluye:",o:[{l:"A",t:"Solo salud"},{l:"B",t:"Factores múltiples"},{l:"C",t:"Solo economía"},{l:"D",t:"Solo familia"}],c:"B"},
{id:120,q:"El objetivo final del cuidado geriátrico es:",o:[{l:"A",t:"Curar"},{l:"B",t:"Bienestar integral"},{l:"C",t:"Control"},{l:"D",t:"Aislar"}],c:"B"}
]},
{"block":3,"title":"Casos Prácticos","icon":"🏥","range":"121-180","questions":[
{id:121,q:"Usuario con desorientación brusca tras infección. Lo más probable es:",o:[{l:"A",t:"Demencia"},{l:"B",t:"Delirium"},{l:"C",t:"Depresión"},{l:"D",t:"Ansiedad"}],c:"B"},
{id:122,q:"Usuaria dependiente rechaza comer. Actuación inicial:",o:[{l:"A",t:"Forzar alimentación"},{l:"B",t:"Comunicar y observar"},{l:"C",t:"Ignorar"},{l:"D",t:"Administrar medicación"}],c:"B"},
{id:123,q:"Familiar grita e insulta al usuario. Se trata de:",o:[{l:"A",t:"Maltrato físico"},{l:"B",t:"Maltrato psicológico"},{l:"C",t:"Negligencia"},{l:"D",t:"Accidente"}],c:"B"},
{id:124,q:"Usuario con pérdida progresiva de memoria y autonomía:",o:[{l:"A",t:"Delirium"},{l:"B",t:"Demencia"},{l:"C",t:"Estrés"},{l:"D",t:"Ansiedad"}],c:"B"},
{id:125,q:"En un CED, usuario mejora su movilidad. Esto indica:",o:[{l:"A",t:"Empeoramiento"},{l:"B",t:"Mantenimiento funcional"},{l:"C",t:"Curación total"},{l:"D",t:"Alta hospitalaria"}],c:"B"},
{id:126,q:"Según Ley 7/1985, competencias municipales deben ejercerse:",o:[{l:"A",t:"Libremente"},{l:"B",t:"En el marco de la ley"},{l:"C",t:"Sin control"},{l:"D",t:"Judicialmente"}],c:"B"},
{id:127,q:"El Pleno adopta acuerdos mediante:",o:[{l:"A",t:"Decreto"},{l:"B",t:"Votación"},{l:"C",t:"Orden"},{l:"D",t:"Resolución"}],c:"B"},
{id:128,q:"El personal eventual se caracteriza por:",o:[{l:"A",t:"Permanencia"},{l:"B",t:"Confianza política"},{l:"C",t:"Estabilidad"},{l:"D",t:"Oposición"}],c:"B"},
{id:129,q:"El principio de objetividad implica:",o:[{l:"A",t:"Actuar según preferencias"},{l:"B",t:"Actuar según criterios profesionales"},{l:"C",t:"Actuar sin normas"},{l:"D",t:"Actuar con favoritismo"}],c:"B"},
{id:130,q:"La vulneración del deber de confidencialidad puede suponer:",o:[{l:"A",t:"Reconocimiento"},{l:"B",t:"Sanción"},{l:"C",t:"Ascenso"},{l:"D",t:"Incentivo"}],
